include_recipe "libcec::default"
include_recipe "xbmc::default"
include_recipe "sabnzbd::default"
include_recipe "sickbeard::default"
include_recipe "couchpotato::default"
include_recipe "htpc::nginx"
